theme: minima
title: "Raspberry Pi Bramble Home"
baseurl: "/rpi-bramble"
collections:
  site_content:
    output: true
    # order:
    #   - 2024-03-12-bill-of-materials.md
    #   - 2024-03-12-assembly-instructions.md
    #   - 2024-03-26-OS-setup.md
    #   - 2024_03_29-install-munge.md
    sort_by: order
defaults:
  -
    scope: 
      path: ""
      type: "site_content"
    values:
      layout: "site_content"
      toc: true
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "site_content"
      toc: true

favicon_svg: assets/images/RPiOnQuillOnScroll.svg
favicon_png: assets/images/RPiOnQuillOnScroll.png
favicon_ico: assets/images/RPiOnQuillOnScroll.ico
# favicon:
#   source: /assets/images/RPiOnQuillOnScroll.svg
#   dest: /assets/images/
#   type: svg

# Note 1: autosidebar takes precedence over sidebar.
#         If the autosidebar option is present, it will trigger.
#         If there is an index page inside a subdirectory (and 
#         the subdirectory itself doesn't have an index page another
#         way), it will be promoted to be the page listing for that
#         subdirectory.
# Note 2: The autoindex option, if present, will also automatically
#         create an index page for any directory that doesn't have
#         one (a manual index file inside the directory will take
#         precedence).
autosidebar:
  autoindex:

sidebar:
  # Note 1: An id can be used to lookup the title/url of a page. 
  #         Alternatively, a title/url attribute can be supplied
  #         to override the automatic lookup.
  # Note 2: The id to be supplied here should match the id
  #         auto-generated from the page filename, NOT the one
  #         in the id field defined in the page metadata in the
  #         file itself.
  # Note 3: The id auto-generated from the page filename is
  #         basically the filename with both the date at the
  #         beginning (including the next dash separator) and
  #         the file extension at the end (.md) removed. It is
  #         also case-sensitive.
  #         So, the id for filename `2020-01-01-Example-page.md`
  #         would be `Example-page`.
  - title: "Steps"
    children:
      # - id: test-file-in-subdir
      #   title: Test Subdir File
      - id: bill-of-materials
      - id: assembly-instructions
      # - id: os-setup
      - id: OS-setup
      # - id: setup-port-switch
      - id: setup-ethernet-switch-routing
      - id: shared-storage
      - id: install-munge
      - id: install-libaio
      - id: install-ncurses
      - id: install-mysql
      - id: install-slurm
  - title: Menu Item with SubItems
    children: 
      - title: child-1-id
        children:
          - title: sub-child
      - title: child-2-id

toc:
  ordered_list: true
  list_class: sidetoc-toc

# debug: true

# permalink: /:categories/:year/:month/:day/:title:output_ext

plugins:
# - jekyll-menus
- jekyll-toc
# - jekyll-favicon
